# Generated by Django 2.1.4 on 2018-12-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20181213_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentimage',
            name='image',
            field=models.BinaryField(),
        ),
    ]
