# Generated by Django 2.1.4 on 2018-12-14 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20181213_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('P', 'Primary'), ('S', 'Secondary')], default='P', max_length=1)),
                ('std_code', models.CharField(max_length=5)),
                ('number', models.IntegerField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.AlterField(
            model_name='studentaddress',
            name='address_type',
            field=models.CharField(choices=[('TMP', 'Temporary'), ('PMT', 'Permanent')], default='PMT', max_length=3),
        ),
        migrations.AlterField(
            model_name='studentaddress',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentaddress',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentaddress',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentaddress',
            name='pincode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentaddress',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
