# Generated by Django 2.1.4 on 2018-12-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20181214_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcontact',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
