# Generated by Django 2.1.4 on 2018-12-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20181216_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
