# Generated by Django 2.1.4 on 2018-12-17 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_student_mother_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentimage',
            name='student_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
