# Generated by Django 2.0.8 on 2018-12-20 09:28

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20181220_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=student.models.student_image_handler),
        ),
    ]
